PREFIX void: <http://rdfs.org/ns/void#>

# list classes and their occurences in the dataset
CONSTRUCT {
    ?datasetUri a void:Dataset;
    void:classPartition [
        void:class ?type;
        void:entities ?total;
    ] .
}
WHERE {
    SELECT (COUNT(?type) as ?total) ?type { ?s a ?type } GROUP BY ?type
}
