PREFIX void: <http://rdfs.org/ns/void#>

# count objects with no blank node or URI as value
CONSTRUCT {
    datasetUri a void:Dataset;
    void:distinctObjects ?total .
}
WHERE {
  ?grapOpen
  SELECT (COUNT(?object) as ?total) {
    ?subject ?property ?object .
    FILTER(!isBlank(?object))
    FILTER(!isUri(?object))
    ?additionalFilter
  }
  ?graphClose
}