PREFIX void: <http://rdfs.org/ns/void#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX nde: <https://www.netwerkdigitaalerfgoed.nl/def#>

# Some prefixes are used only in the subject filter (see catalog definitions)
PREFIX schema: <http://schema.org/>

# count objects with no blank node or URI as value
CONSTRUCT {
    {{&dataset-uri}} a void:Dataset;
    rdfs:label "number of objects with literal value" ;
    nde:distinctObjectsLiteral ?total .
}
WHERE {
    {{&graph-open}}
    SELECT (COUNT(?object) as ?total) {
        ?subject ?property ?object .
        FILTER(!isBlank(?object))
        FILTER(!isUri(?object))
        {{&subject-filter}}
    }
    {{&graph-close}}
}
