PREFIX void: <http://rdfs.org/ns/void#>

# list classes and their occurences in the dataset
CONSTRUCT {
    {{&dataset-uri}} a void:Dataset;
    void:classPartition [
        void:class ?property;
        void:entities ?total;
    ] .
}
WHERE {
    {{&graph-open}}
    SELECT (COUNT(?property) as ?total) ?property {
        ?subject ?property ?object .
        {{&subject-filter}}
    }
    GROUP BY ?property
    {{&graph-close}}
}
