PREFIX void: <http://rdfs.org/ns/void#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Some prefixes are used only in the subject filter (see catalog definitions)
PREFIX schema: <http://schema.org/>

# list properties and their occurences 
CONSTRUCT {
    {{&dataset-uri}} a void:Dataset;
    void:propertyPartition [
        rdfs:label ?label ;
        void:property ?property;
        void:entities ?total;
    ] .
}
WHERE {
    {{&graph-open}}
    SELECT (COUNT(?property) as ?total) ?property ?label {
        ?subject ?property ?object .
        BIND(CONCAT("totals for property ", STR(?property)) as ?label)
        {{&subject-filter}}
    }
    GROUP BY ?property ?label
    {{&graph-close}}
}
